name: release

on:
  workflow_dispatch:
    inputs:
      manual:
        description: 'manual build and publish'
  schedule:
    - cron: '0 0 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: VergilGao
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/vergilgao/openwrt-compiler:latest
        build-args: |
          VERSION=${{ env.BUILD_VERSION }}
          BUILD_DATE=${{ env.BUILD_DATE }}
        cache-from: type=registry,ref=ghcr.io/vergilgao/openwrt-compiler:buildcache
        cache-to: type=registry,ref=ghcr.io/vergilgao/openwrt-compiler:buildcache,mode=max

    - name: purge packages
      uses: dylanratcliffe/delete-untagged-containers@main
      with:
        package_name: openwrt-compiler
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}    
